#!/bin/bash

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ] || [ $1 != digispark ] || ( [ -n "$2" ] && [ $2 != bootloader ] && [ $2 != identify-model ] ); then
    echo ""
    echo "x-board-install expects a command the following format:"
    echo ""
    echo "x-board-install digispark [bootloader|identify-model]"
    echo ""
    
    exit -1
fi


if [ -z "$2" ]; then
    ./micronucleus images/digispark/main.hex
    exit
fi

if [ $2 == bootloader ]; then
    ./micronucleus images/digispark/bootloader.hex
fi

if [ $2 == identify-model ]; then
    ./micronucleus images/digispark/identify-model.hex
fi